### ISSUE TITLE
Delegate behaviour when maxSenderAmount hits 0

### ISSUE THREAD

**Issue by alicevhenshaw** [airswap/airswap-protocols#259] opened 2019-11-01 15:37 UTC
Some suggested functionality:

- If a Rule hits `maxSenderAmount` of 0, it should automatically call `indexer.unsetIntent()` to remove itself from the indexer as it can no longer trade.
- If a Rule hits `maxSenderAmount` of 0, it should automatically delete the rule from the mapping

**Comment by dmosites** [comment] 2019-11-01 16:10
Duplicate of #243, see for discussion

**Closed** 2019-11-01 16:13 UTC
Labels: duplicate, to discuss
